//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IPTVChannelEditor.rc
//
#define IDM_ABOUTBOX                    16
#define IDR_POPUP_TRAY                  17
#define IDB_PNG_QR                      101
#define IDD_ABOUTBOX                    102
#define IDD_CUSTOM_PLAYLIST             103
#define IDD_CUSTOM_URL                  104
#define IDD_DIALOG_ACCESS_INFO          105
#define IDD_DIALOG_FILTER               106
#define IDD_DIALOG_NEW_CHANNELS_LIST    107
#define IDD_DIALOG_NEW_CHANNEL          108
#define IDD_MAIN_SETTINGS_PAGE          109
#define IDD_EDEMCHANNELEDITOR_DIALOG    110
#define IDD_UPDATE_SETTINGS_PAGE        111
#define IDR_MENU_SPLIT                  111
#define IDR_ACCELERATOR_TABLE           112
#define IDR_MENU_CHANNEL                113
#define IDR_MENU_PLAYLIST               114
#define IDS_ABOUTBOX                    115
#define IDS_LANGUAGE                    116
#define IDS_STRING_FILE                 117
#define IDS_STRING_URL                  118
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_ICONS_LIST           129
#define IDD_DIALOG_ACCESS_INFO_PASS     130
#define IDD_DIALOG_ACCESS_INFO_PIN      131
#define IDD_DIALOG_ICON_LINK            132
#define IDD_PATHS_SETTINGS_PAGE         133
#define IDS_STRING_ERR_SOURCE_NOT_SET   140
#define IDS_STRING_ERR_CANT_DOWNLOAD_PLAYLIST 141
#define IDS_STRING_ERR_EMPTY_PLAYLIST   142
#define IDS_STRING_ERR_THREAD_NOT_START 143
#define IDS_STRING_WRN_NOT_SAVED        144
#define IDS_STRING_WRN_DELETE_CHANNEL   145
#define IDS_STRING_WRN_CHANNEL_EXIST    146
#define IDS_STRING_WRN_CHANNEL_ID_EXIST 147
#define IDS_STRING_WRN_NON_ASCII        148
#define IDS_STRING_WRN_NON_ASCII_LIST   149
#define IDS_STRING_INFO_CREATE_SUCCESS  150
#define IDS_STRING_INFO_NOT_FOUND       151
#define IDS_STRING_INFO_RESTART_NEED    152
#define IDS_STRING_FMT_CHANNELS         153
#define IDS_STRING_FMT_PLAYLIST_FLT     154
#define IDS_STRING_FMT_PLAYLIST         155
#define IDS_STRING_FMT_CHANNELS_READED  156
#define IDS_STRING_FMT_STREAM_INFO      157
#define IDS_STRING_FMT_CHANNELS_TOOLTIP1 158
#define IDS_STRING_FMT_CHANNELS_TOOLTIP2 159
#define IDS_STRING_FMT_CHANNELS_TOOLTIP3 160
#define IDS_STRING_FMT_PLAYLIST_TOOLTIPS 161
#define IDS_STRING_YES                  162
#define IDS_STRING_NO                   163
#define IDS_STRING_CUSTOM               164
#define IDS_STRING_DONATE               165
#define IDS_STRING_COMBO_PLUGIN_TYPE    166
#define IDS_STRING_COMBO_CHANNELS       167
#define IDS_STRING_COMBO_PLAYLIST       168
#define IDS_STRING_BUTTON_ADD_NEW_CHANNELS_LIST 169
#define IDS_STRING_EDIT_SEARCH          170
#define IDS_STRING_BUTTON_SEARCH_NEXT   171
#define IDS_STRING_EDIT_URL_ID          172
#define IDS_STRING_BUTTON_TEST_EPG      173
#define IDS_STRING_EDIT_EPG1_ID         174
#define IDS_STRING_EDIT_EPG2_ID         175
#define IDS_STRING_CHECK_CUSTOMIZE      176
#define IDS_STRING_CHECK_ARCHIVE        177
#define IDS_STRING_EDIT_ARCHIVE_DAYS    178
#define IDS_STRING_CHECK_ADULT          179
#define IDS_STRING_BUTTON_CACHE_ICON    180
#define IDS_STRING_BUTTON_SAVE          181
#define IDS_STRING_BUTTON_PACK          182
#define IDS_STRING_BUTTON_SETTINGS      183
#define IDS_STRING_SHOW_CHANGED         184
#define IDS_STRING_ACCOUNT_SETTINGS     185
#define IDS_STRING_BUTTON_DOWNLOAD_PLAYLIST 186
#define IDS_STRING_EDIT_PL_SEARCH       187
#define IDS_STRING_BUTTON_PL_SEARCH_NEXT 188
#define IDS_STRING_BUTTON_PL_FILTER     189
#define IDS_STRING_STATIC_ICON          190
#define IDS_STRING_EDIT_ARCHIVE_CHECK_DAYS 191
#define IDS_STRING_EDIT_ARCHIVE_CHECK_HOURS 192
#define IDS_STRING_EDIT_TIME_SHIFT      193
#define IDS_STRING_EDIT_INFO_VIDEO      194
#define IDS_STRING_EDIT_INFO_AUDIO      195
#define IDS_STRING_COMBO_STREAM_TYPE    196
#define IDS_STRING_COMBO_ICON_SOURCE    197
#define IDS_STRING_BUTTON_STOP          198
#define IDS_STRING_BUTTON_UPDATE_CHANGED 199
#define IDS_STRING_BUTTON_CHECK_ARCHIVE 200
#define IDS_STRING_WARN_DELETE_ITEMS    201
#define IDS_STRING_ERR_FAILED_PACK      202
#define IDS_STRING_ERR_FAILED_PACK_PLUGIN 203
#define IDS_STRING_INFO_CREATE_ALL_SUCCESS 204
#define IDS_STRING_LOAD_CHANNELS_MASK   205
#define IDS_STRING_LOAD_ICON            206
#define IDS_STRING_LOAD_PLAYLIST        207
#define IDS_STRING_LOAD_ICONS_TITLE     208
#define IDS_STRING_ADD_NEW_CHANNELS     209
#define IDS_STRING_NOT_ADDED            210
#define IDS_STRING_ALREADY_RUNNING      211
#define IDS_STRING_ENABLE_CHANNEL       212
#define IDS_STRING_ENABLE_CATEGORY      213
#define IDS_STRING_ERR_LOAD_CHANNELS_LIST 214
#define IDS_STRING_ERR_REGEX            215
#define IDS_STRING_ERR_NO_CHANNELS      216
#define IDS_STRING_STANDARD             217
#define IDS_STRING_UPDATE_AVAILABLE     218
#define IDS_STRING_UPDATE_DONE          219
#define IDS_STRING_ERR_UPDATE           220
#define IDS_STRING_NO_CHANNELS          221
#define IDS_STRING_STATUS               222
#define IDS_STRING_STATUS_TEXT          223
#define IDS_STRING_SHOW_UNKNOWN         224
#define IDS_STRING_ERR_FILE_MISSING     225
#define IDS_STRING_ERR_NOT_PORTABLE     226
#define IDS_STRING_ERR_TRAY_ICON        227
#define IDS_STRING_DEVICE_ID            228
#define IDS_STRING_SERVER_ID            229
#define IDC_BUTTON_ABOUT                1001
#define IDC_CHECK_CASE_HIDE             1002
#define IDC_CHECK_REGEX_HIDE            1003
#define IDC_BUTTON_CACHE_ICON           1005
#define IDC_BUTTON_DOWNLOAD_PLAYLIST    1006
#define IDC_BUTTON_GET                  1007
#define IDC_BUTTON_IMPORT               1010
#define IDC_BUTTON_ADD_NEW_CHANNELS_LIST 1011
#define IDC_BUTTON_CHOOSE_PLAYLIST      1012
#define IDC_BUTTON_PL_FILTER            1014
#define IDC_BUTTON_PL_SEARCH_NEXT       1015
#define IDC_BUTTON_SAVE                 1017
#define IDC_BUTTON_SEARCH_NEXT          1018
#define IDC_BUTTON_SETTINGS             1019
#define IDC_BUTTON_STOP                 1020
#define IDC_BUTTON_TEST_EPG             1021
#define IDC_BUTTON_UPDATE_CHANGED       1022
#define IDC_BUTTON_CHECK_ARCHIVE        1024
#define IDC_CHECK_ADULT                 1025
#define IDC_CHECK_ARCHIVE               1026
#define IDC_CHECK_CASE_SHOW             1027
#define IDC_CHECK_CUSTOMIZE             1028
#define IDC_CHECK_GLOBAL                1029
#define IDC_CHECK_PL_ARCHIVE            1030
#define IDC_CHECK_REGEX_SHOW            1031
#define IDC_CHECK_NOT_ADDED             1032
#define IDC_CHECK_SHOW_CHANGED          1033
#define IDC_COMBO_CHANNELS              1034
#define IDC_COMBO_PLAYLIST              1035
#define IDC_COMBO_SORT                  1036
#define IDC_CUSTOM_PLAYLIST             1037
#define IDC_EDIT_ARCHIVE_CHECK_DAYS     1038
#define IDC_EDIT_ARCHIVE_CHECK_HOURS    1039
#define IDC_EDIT_CATEGORY               1040
#define IDC_EDIT_DOMAIN                 1041
#define IDC_EDIT_PASSWORD               1042
#define IDC_EDIT_EPG1_ID                1043
#define IDC_EDIT_INFO_AUDIO             1044
#define IDC_EDIT_INFO_VIDEO             1045
#define IDC_EDIT_KEY                    1046
#define IDC_EDIT_LOGIN                  1047
#define IDC_EDIT_VP_KEY                 1047
#define IDC_EDIT_PL_SEARCH              1048
#define IDC_EDIT_PLAYLIST_URL           1049
#define IDC_EDIT_NAME                   1050
#define IDC_EDIT_SEARCH                 1051
#define IDC_EDIT_STREAM_URL             1052
#define IDC_EDIT_EPG2_ID                1054
#define IDC_EDIT_URL_ID                 1055
#define IDC_EDIT_URL                    1056
#define IDC_MFCEDITBROWSE_PLAYER        1057
#define IDC_MFCEDITBROWSE_PROBE         1058
#define IDC_MFCLINK_DONATE              1059
#define IDC_PROGRESS_LOAD               1060
#define IDC_SPIN_ARCHIVE_CHECK_HOURS    1061
#define IDC_SPIN_ARCHIVE_CHECK_DAYS     1062
#define IDC_STATIC_APP_TITLE            1064
#define IDC_STATIC_CHANNELS             1066
#define IDC_STATIC_ICON                 1067
#define IDC_STATIC_ICON_NAME            1068
#define IDC_STATIC_PL_ICON              1069
#define IDC_STATIC_PL_ICON_NAME         1070
#define IDC_STATIC_PL_ID                1071
#define IDC_STATIC_PL_EPG               1072
#define IDC_STATIC_PLAYLIST             1073
#define IDC_STATIC_QR                   1074
#define IDC_STATIC_TITLE                1075
#define IDC_STATIC_PROGRESS_INFO        1076
#define IDC_TREE_CHANNELS               1077
#define IDC_TREE_PLAYLIST               1078
#define IDC_MFCLINK_DONATE_ABOUT        1079
#define IDC_STATIC_STREAM_TYPE          1080
#define IDC_EDIT_PL_ARCHIVE_DAYS        1081
#define IDC_EDIT_TIME_SHIFT             1082
#define IDC_SPIN_TIME_SHIFT             1083
#define IDC_COMBO_PLUGIN_TYPE           1084
#define IDC_COMBO_ICON_SOURCE           1085
#define IDC_LIST_ICONS                  1086
#define IDC_COMBO_STREAM_TYPE           1087
#define IDC_STATIC_SEARCH               1088
#define IDC_EDIT_ARCHIVE_DAYS           1089
#define IDC_COMBO_TYPE                  1090
#define IDC_CHECK_AUTO_SYNC_CHANNELS    1091
#define IDC_LIST_INFO                   1092
#define IDC_STATIC_LOGIN                1096
#define IDC_STATIC_PASSWORD             1097
#define IDC_STATIC_DEVICE_ID            1100
#define IDC_CHECK_EMBED                 1101
#define IDC_STATIC_VERSION              1102
#define IDC_CHECK_EMBED2                1102
#define IDC_CHECK_EMBED_VP              1102
#define IDC_EDIT_EPG                    1103
#define IDC_RICHEDIT_EPG                1104
#define IDC_RADIO_EPG1                  1105
#define IDC_RADIO_EPG2                  1106
#define IDC_EDIT_STREAM_THREADS         1107
#define IDC_SPIN_STREAM_THREADS         1108
#define IDC_COMBO_LANG                  1109
#define IDC_SPLIT_BUTTON_PACK           1110
#define IDC_MFCEDITBROWSE_CH_LIST_PATH  1111
#define IDC_MFCEDITBROWSE_PLUGINS_PATH  1112
#define IDC_STATIC_ICON_SIZE            1113
#define IDC_CHECK_CMP_TITLE             1114
#define IDC_CHECK_CMP_ICON              1115
#define IDC_CHECK_CMP_EPG1              1116
#define IDC_CHECK_CMP_EPG2              1117
#define IDC_CHECK_CMP_ARCHIVE           1118
#define IDC_CHECK_AUTO_HIDE             1119
#define IDC_COMBO_STRING_SHOW           1120
#define IDC_COMBO_STRING_HIDE           1121
#define IDC_CHECK_SHOW_MATCHED          1122
#define IDC_CHECK_HIDE_MATCHED          1123
#define IDC_SPIN_CHECK_UPDATE           1124
#define IDC_COMBO_DEVICE_ID             1124
#define IDC_SPLIT_BUTTON_UPDATE         1125
#define IDC_EDIT_UPDATE_FREQ            1126
#define IDC_CHECK_CHANNELS              1127
#define IDC_STATIC_VPORTAL              1127
#define IDC_CHECK_SHOW_UNKNOWN          1128
#define ID_ADD_CATEGORY                 32771
#define ID_NEW_CHANNEL                  32772
#define ID_BTN_GET                      32773
#define ID_CHANNEL_DOWN                 32774
#define ID_CHANNEL_UP                   32775
#define ID_CHANNELMENU_PLAYARCHIVE      32776
#define ID_CHANNELMENU_SORTBY           32777
#define ID_EDIT_RENAME                  32778
#define ID_GET_STREAM_INFO              32779
#define ID_RESTORE                      32780
#define ID_NEW_CATEGORY                 32784
#define ID_PLAY_ARCHIVE                 32785
#define ID_PLAY_STREAM                  32786
#define ID_REMOVE                       32790
#define ID_SAVE                         32791
#define ID_TOGGLE_CHANNEL               32792
#define ID_UPDATE_CHANNEL               32793
#define ID_PLAYLISTMENU_SUBMENU         32795
#define ID_SYNC_TREE_ITEM               32796
#define ID_SORT_CATEGORY                32797
#define ID_ADD_TO_FAVORITE              32798
#define ID_CLEAR_STREAM_INFO            32799
#define ID_MAKE_ALL                     32800
#define ID_TOGGLE_CATEGORY              32801

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1128
#define _APS_NEXT_SYMED_VALUE           1180
#endif
#endif
