//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EdemChannelEditor.rc
//
#define IDM_ABOUTBOX                    16
#define IDB_PNG_QR                      101
#define IDD_ABOUTBOX                    102
#define IDD_CUSTOM_PLAYLIST             103
#define IDD_CUSTOM_URL                  104
#define IDD_DIALOG_ACCESS_INFO          105
#define IDD_DIALOG_FILTER               106
#define IDD_DIALOG_NEW_CATEGORY         107
#define IDD_DIALOG_NEW_CHANNEL          108
#define IDD_DIALOG_SETTINGS             109
#define IDD_EDEMCHANNELEDITOR_DIALOG    110
#define IDR_ACCELERATOR_TABLE           112
#define IDR_MENU_CHANNEL                113
#define IDR_MENU_PLAYLIST               114
#define IDS_ABOUTBOX                    115
#define IDR_MAINFRAME                   128
#define IDC_BUTTON_ABOUT                1001
#define IDC_BUTTON_ACCESS_INFO          1002
#define IDC_BUTTON_ADD_CATEGORY         1003
#define IDC_BUTTON_ADD_TO_SHOW          1004
#define IDC_BUTTON_CACHE_ICON           1005
#define IDC_BUTTON_DOWNLOAD_PLAYLIST    1006
#define IDC_BUTTON_GET                  1007
#define IDC_BUTTON_GET_INFO             1008
#define IDC_BUTTON_IMPORT               1010
#define IDC_BUTTON_LOAD_CHANNELS        1011
#define IDC_BUTTON_LOAD_PLAYLIST        1012
#define IDC_BUTTON_PACK                 1013
#define IDC_BUTTON_PL_FILTER            1014
#define IDC_BUTTON_PL_SEARCH_NEXT       1015
#define IDC_BUTTON_REMOVE_FROM_SHOW     1016
#define IDC_BUTTON_SAVE                 1017
#define IDC_BUTTON_SEARCH_NEXT          1018
#define IDC_BUTTON_SETTINGS             1019
#define IDC_BUTTON_SORT                 1020
#define IDC_BUTTON_TEST_EPG             1021
#define IDC_BUTTON_TEST_TVG             1022
#define IDC_BUTTON_UPDATE_ICON          1023
#define IDC_BUTTON_TEST_EPG2            1024
#define IDC_BUTTON_CHECK_ARCHIVE        1024
#define IDC_CHECK_ADULT                 1025
#define IDC_CHECK_ARCHIVE               1026
#define IDC_CHECK_CASE                  1027
#define IDC_CHECK_CUSTOMIZE             1028
#define IDC_CHECK_GLOBAL                1029
#define IDC_CHECK_PL_ARCHIVE            1030
#define IDC_CHECK_REGEX                 1031
#define IDC_CHECK_REGEX2                1032
#define IDC_COMBO_CATEGORY              1033
#define IDC_COMBO_CHANNELS              1034
#define IDC_COMBO_PLAYLIST              1035
#define IDC_COMBO_SORT                  1036
#define IDC_CUSTOM_PLAYLIST             1037
#define IDC_EDIT1                       1038
#define IDC_EDIT_ARCHIVE_CHECK          1039
#define IDC_EDIT_CATEGORY               1040
#define IDC_EDIT_DOMAIN                 1041
#define IDC_EDIT_DOMAIN2                1042
#define IDC_EDIT_EPG_ID                 1043
#define IDC_EDIT_INFO_AUDIO             1044
#define IDC_EDIT_INFO_VIDEO             1045
#define IDC_EDIT_KEY                    1046
#define IDC_EDIT_NEXT_EPG               1047
#define IDC_EDIT_PL_SEARCH              1048
#define IDC_EDIT_PLAYLIST_URL           1049
#define IDC_EDIT_PREV_EPG               1050
#define IDC_EDIT_SEARCH                 1051
#define IDC_EDIT_STREAM_URL             1052
#define IDC_EDIT_STRING                 1053
#define IDC_EDIT_TVG_ID                 1054
#define IDC_EDIT_URL_ID                 1055
#define IDC_LIST_CATEGORIES             1056
#define IDC_MFCEDITBROWSE_PLAYER        1057
#define IDC_MFCEDITBROWSE_PROBE         1058
#define IDC_MFCLINK_DONATE              1059
#define IDC_PROGRESS_LOAD               1060
#define IDC_SPIN_ARCHIVE_CHECK          1061
#define IDC_SPIN_NEXT                   1062
#define IDC_SPIN_PREV                   1063
#define IDC_STATIC_APP_TITLE            1064
#define IDC_STATIC_CATEGORY_ICON        1065
#define IDC_STATIC_CHANNELS             1066
#define IDC_STATIC_ICON                 1067
#define IDC_STATIC_ICON_NAME            1068
#define IDC_STATIC_PL_ICON              1069
#define IDC_STATIC_PL_ICON_NAME         1070
#define IDC_STATIC_PL_ID                1071
#define IDC_STATIC_PL_TVG               1072
#define IDC_STATIC_PLAYLIST             1073
#define IDC_STATIC_QR                   1074
#define IDC_STATIC_TITLE                1075
#define IDC_STATIC_VERSION              1076
#define IDC_TREE_CHANNELS               1077
#define IDC_TREE_PLAYLIST               1078
#define ID_ADD_CATEGORY                 32771
#define ID_ADD_CHANNEL                  32772
#define ID_BTN_GET                      32773
#define ID_CHANNEL_DOWN                 32774
#define ID_CHANNEL_UP                   32775
#define ID_CHANNELMENU_PLAYARCHIVE      32776
#define ID_CHANNELMENU_SORTBY           32777
#define ID_EDIT_RENAME                  32778
#define ID_GET_STREAM_INFO              32779
#define ID_GET_STREAM_INFO_ALL          32780
#define ID_NEW_CATEGORY                 32784
#define ID_PLAY_ARCHIVE                 32785
#define ID_PLAY_STREAM                  32786
#define ID_PLAY_STREAM_PL               32787
#define ID_PLAYARCHIVE_                 32788
#define ID_PLAYARCHIVE_32796            32789
#define ID_PLAYARCHIVE_32797            32790
#define ID_PLAYARCHIVE_32798            32791
#define ID_REMOVE_CATEGORY              32792
#define ID_REMOVE_CHANNEL               32793
#define ID_SAVE                         32794
#define ID_TOGGLE_CHANNEL               32795
#define ID_UPDATE_CHANNEL               32796
#define ID_UPDATE_ICON                  32797

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           1179
#endif
#endif
