//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IPTVChannelEditor.rc
//
#define IDM_ABOUTBOX                    16
#define IDR_POPUP_TRAY                  17
#define IDR_MENU_CHANGED                18
#define IDB_PNG_QR                      101
#define IDD_ABOUTBOX                    102
#define IDD_CUSTOM_PLAYLIST             103
#define IDD_CUSTOM_URL                  104
#define IDD_DIALOG_VOD                  105
#define IDD_DIALOG_FILTER               106
#define IDD_DIALOG_NEW_CHANNELS_LIST    107
#define IDD_DIALOG_NEW_CHANNEL          108
#define IDD_MAIN_SETTINGS_PAGE          109
#define IDD_EDEMCHANNELEDITOR_DIALOG    110
#define IDD_UPDATE_SETTINGS_PAGE        111
#define IDR_MENU_SPLIT                  111
#define IDD_DIALOG_EPG_LIST             112
#define IDR_ACCELERATOR_TABLE           112
#define IDR_MENU_CHANNEL                113
#define IDR_MENU_PLAYLIST               114
#define IDS_ABOUTBOX                    115
#define IDS_LANGUAGE                    116
#define IDS_STRING_FILE                 117
#define IDS_STRING_URL                  118
#define IDD_DIALOG_URL                  119
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_ICONS_LIST           129
#define IDD_DIALOG_ACCESS_INFO          131
#define IDD_DIALOG_ICON_LINK            132
#define IDD_PATHS_SETTINGS_PAGE         133
#define IDD_DIALOG_PLUGIN_CONFIG        134
#define IDS_STRING_ERR_SOURCE_NOT_SET   140
#define IDS_STRING_ERR_CANT_DOWNLOAD_PLAYLIST 141
#define IDS_STRING_ERR_EMPTY_PLAYLIST   142
#define IDS_STRING_ERR_THREAD_NOT_START 143
#define IDS_STRING_WRN_NOT_SAVED        144
#define IDS_STRING_WRN_DELETE_CHANNEL   145
#define IDS_STRING_WRN_CHANNEL_EXIST    146
#define IDS_STRING_WRN_CHANNEL_ID_EXIST 147
#define IDS_STRING_WRN_NON_ASCII        148
#define IDS_STRING_WRN_NON_ASCII_LIST   149
#define IDS_STRING_INFO_CREATE_SUCCESS  150
#define IDS_STRING_INFO_NOT_FOUND       151
#define IDS_STRING_INFO_RESTART_NEED    152
#define IDS_STRING_FMT_CHANNELS         153
#define IDS_STRING_FMT_PLAYLIST_FLT     154
#define IDS_STRING_FMT_PLAYLIST         155
#define IDS_STRING_FMT_CHANNELS_READED  156
#define IDS_STRING_FMT_STREAM_INFO      157
#define IDS_STRING_FMT_CHANNELS_TOOLTIP1 158
#define IDS_STRING_FMT_CHANNELS_TOOLTIP2 159
#define IDS_STRING_FMT_CHANNELS_TOOLTIP3 160
#define IDS_STRING_FMT_PLAYLIST_TOOLTIPS 161
#define IDS_STRING_YES                  162
#define IDS_STRING_NO                   163
#define IDS_STRING_CUSTOM               164
#define IDS_STRING_DONATE               165
#define IDS_STRING_COMBO_PLUGIN_TYPE    166
#define IDS_STRING_COMBO_CHANNELS       167
#define IDS_STRING_COMBO_PLAYLIST       168
#define IDS_STRING_BUTTON_ADD_NEW_CHANNELS_LIST 169
#define IDS_STRING_EDIT_SEARCH          170
#define IDS_STRING_BUTTON_SEARCH_NEXT   171
#define IDS_STRING_EDIT_URL_ID          172
#define IDS_STRING_BUTTON_TEST_EPG      173
#define IDS_STRING_EDIT_EPG1_ID         174
#define IDS_STRING_EDIT_EPG2_ID         175
#define IDS_STRING_CHECK_CUSTOMIZE      176
#define IDS_STRING_CHECK_ARCHIVE        177
#define IDS_STRING_EDIT_ARCHIVE_DAYS    178
#define IDS_STRING_CHECK_ADULT          179
#define IDS_STRING_BUTTON_CACHE_ICON    180
#define IDS_STRING_BUTTON_SAVE          181
#define IDS_STRING_BUTTON_PACK          182
#define IDS_STRING_BUTTON_SETTINGS      183
#define IDS_STRING_SHOW_CHANGED         184
#define IDS_STRING_ACCOUNT_SETTINGS     185
#define IDS_STRING_BUTTON_DOWNLOAD_PLAYLIST 186
#define IDS_STRING_EDIT_PL_SEARCH       187
#define IDS_STRING_BUTTON_PL_SEARCH_NEXT 188
#define IDS_STRING_BUTTON_PL_FILTER     189
#define IDS_STRING_STATIC_ICON          190
#define IDS_STRING_EDIT_ARCHIVE_CHECK_DAYS 191
#define IDS_STRING_EDIT_ARCHIVE_CHECK_HOURS 192
#define IDS_STRING_EDIT_TIME_SHIFT      193
#define IDS_STRING_EDIT_INFO_VIDEO      194
#define IDS_STRING_EDIT_INFO_AUDIO      195
#define IDS_STRING_COMBO_STREAM_TYPE    196
#define IDS_STRING_COMBO_ICON_SOURCE    197
#define IDS_STRING_BUTTON_STOP          198
#define IDS_STRING_BUTTON_UPDATE_CHANGED 199
#define IDS_STRING_BUTTON_CHECK_ARCHIVE 200
#define IDS_STRING_WARN_DELETE_ITEMS    201
#define IDS_STRING_ERR_FAILED_PACK      202
#define IDS_STRING_ERR_FAILED_PACK_PLUGIN 203
#define IDS_STRING_INFO_CREATE_ALL_SUCCESS 204
#define IDS_STRING_LOAD_CHANNELS_MASK   205
#define IDS_STRING_LOAD_ICON            206
#define IDS_STRING_LOAD_PLAYLIST        207
#define IDS_STRING_LOAD_ICONS_TITLE     208
#define IDS_STRING_ADD_NEW_CHANNELS     209
#define IDS_STRING_NOT_ADDED            210
#define IDS_STRING_ALREADY_RUNNING      211
#define IDS_STRING_ENABLE_CHANNEL       212
#define IDS_STRING_ENABLE_CATEGORY      213
#define IDS_STRING_ERR_LOAD_CHANNELS_LIST 214
#define IDS_STRING_ERR_REGEX            215
#define IDS_STRING_ERR_NO_CHANNELS      216
#define IDS_STRING_STANDARD             217
#define IDS_STRING_UPDATE_AVAILABLE     218
#define IDS_STRING_UPDATE_DONE          219
#define IDS_STRING_ERR_UPDATE           220
#define IDS_STRING_NO_CHANNELS          221
#define IDS_STRING_STATUS               222
#define IDS_STRING_STATUS_TEXT          223
#define IDS_STRING_SHOW_UNKNOWN         224
#define IDS_STRING_ERR_FILES_MISSING    225
#define IDS_STRING_ERR_NOT_PORTABLE     226
#define IDS_STRING_ERR_TRAY_ICON        227
#define IDS_STRING_DEVICE_ID            228
#define IDS_STRING_SERVER_ID            229
#define IDS_STRING_APP_TITLE            230
#define IDS_STRING_APP_TITLE_PORTABLE   231
#define IDS_STRING_PLAYLIST             232
#define IDS_STRING_EDEM_STANDARD        234
#define IDS_STRING_EDEM_THEMATIC        235
#define IDS_STRING_COL_INFO             236
#define IDS_STRING_COL_DATA             237
#define IDS_STRING_COL_START            238
#define IDS_STRING_COL_END              239
#define IDS_STRING_COL_TITLE            240
#define IDS_STRING_COL_ICON             241
#define IDS_STRING_COL_CHANNEL_NAME     242
#define IDS_STRING_COL_LOGIN            243
#define IDS_STRING_COL_PASSWORD         244
#define IDS_STRING_COL_TOKEN            245
#define IDS_STRING_COL_DOMAIN           246
#define IDS_STRING_COL_VPORTAL          247
#define IDS_STRING_PAYPAL               248
#define IDS_STRING_YOOMONEY             249
#define IDS_STRING_FMT_MOVIES_READED    250
#define IDS_STRING_ALL                  251
#define IDS_STRING_NONE                 252
#define IDS_STRING_SEASON               253
#define IDS_STRING_EPISODE              254
#define IDS_STRING_VOD_DESC             255
#define IDS_STRING_LOADING              256
#define IDS_STRING_QUALITY_ID           257
#define IDS_STRING_FMT_CHANNELS_ALL     258
#define IDS_STRING_BUTTON_VOD           259
#define IDS_STRING_BUTTON_ABOUT         260
#define IDS_STRING_BUTTON_ADD           261
#define IDS_STRING_BUTTON_REMOVE        262
#define IDS_STRING_BUTTON_NEW_FROM_URL  263
#define IDS_STRING_CHECK_EMBED          266
#define IDS_STRING_COL_COMMENT          267
#define IDS_STRING_COL_SUFFIX           268
#define IDS_STRING_COL_LIST             269
#define IDS_STRING_ERR_SAME_SUFFIX      270
#define IDS_STRING_EDIT_CAPTION         271
#define IDS_STRING_EDIT_ICON            272
#define IDS_STRING_EDIT_BACKGROUND      273
#define IDS_STRING_EDIT_SUFFIX          274
#define IDS_STRING_ERR_DLL_MISSING      275
#define IDS_STRING_ERR_FILE_MISSING     277
#define IDS_STRING_ERR_SETTINGS_MISSING 278
#define IDS_STRING_INFO_W_CREATE_SUCCESS 279
#define IDS_STRING_EDIT_PLUGIN_CHANNELS_WEB_PATH 280
#define IDS_STRING_EDIT_PLUGIN_UPDATE_URL 281
#define IDS_STRING_EDIT_PLUGIN_UPDATE_FILE_URL 282
#define IDS_STRING_EDIT_PLUGIN_UPDATE_VERSION 283
#define IDS_STRING_CHECK_AUTOINCREMENT_VERSION 284
#define IDS_STRING_CHECK_CUSTOM_UPDATE_NAME 285
#define IDS_STRING_EDIT_PLUGIN_UPDATE_NAME 286
#define IDS_STRING_CHECK_CUSTOM_PACKAGE_NAME 287
#define IDS_STRING_EDIT_PLUGIN_PACKAGE_NAME 288
#define IDS_STRING_BOTH_PATH_MUST_FILLED 289
#define IDS_STRING_COMBO_QUALITY        290
#define IDS_STRING_COMBO_SERVER_ID      291
#define IDS_STRING_COMBO_DEVICE_ID      292
#define IDS_STRING_COMBO_PROFILE        293
#define IDS_STRING_COMBO_QUALITY_ID     294
#define IDS_STRING_FILMAX_P1            400
#define IDS_STRING_FILMAX_P2            401
#define IDS_STRING_FILMAX_P3            402
#define IDS_STRING_FILMAX_P4            403
#define IDS_STRING_FILMAX_P5            404
#define IDS_STRING_FILMAX_P6            405
#define IDS_STRING_FILMAX_P7            406
#define IDS_STRING_FILMAX_P8            407
#define IDS_STRING_FILMAX_P9            408
#define IDS_STRING_FILMAX_P10           409
#define IDS_STRING_FILMAX_P11           410
#define IDS_STRING_FILMAX_P12           411
#define IDS_STRING_SHURA_TV_P1          420
#define IDS_STRING_SHURA_TV_P2          421
#define IDS_STRING_CBILLING_TV_P1       430
#define IDS_STRING_CBILLING_TV_P2       431
#define IDS_STRING_CBILLING_TV_P3       432
#define IDS_STRING_VIPLIME_P1           460
#define IDS_STRING_VIPLIME_P2           461
#define IDS_STRING_VIPLIME_P3           462
#define IDS_STRING_VIPLIME_P4           463
#define IDS_STRING_VIPLIME_P5           464
#define IDS_STRING_KINESKOP_P1          470
#define IDS_STRING_KINESKOP_P2          471
#define IDS_STRING_KINESKOP_P3          472
#define IDS_STRING_KINESKOP_P4          473
#define IDS_STRING_MYMAGIC_Q1           480
#define IDS_STRING_MYMAGIC_Q2           481
#define IDS_STRING_MYMAGIC_P0           485
#define IDS_STRING_MYMAGIC_P1           486
#define IDS_STRING_MYMAGIC_P2           487
#define IDS_STRING_MYMAGIC_P3           488
#define IDS_STRING_MYMAGIC_P4           489
#define IDS_STRING_MYMAGIC_P5           490
#define IDS_STRING_MYMAGIC_P6           491
#define IDC_BUTTON_ABOUT                1001
#define IDC_CHECK_CASE_HIDE             1002
#define IDC_CHECK_REGEX_HIDE            1003
#define IDC_BUTTON_CACHE_ICON           1005
#define IDC_BUTTON_DOWNLOAD_PLAYLIST    1006
#define IDC_BUTTON_GET                  1007
#define IDC_BUTTON_IMPORT               1010
#define IDC_BUTTON_ADD_NEW_CHANNELS_LIST 1011
#define IDC_BUTTON_ACCOUNT_SETTINGS     1012
#define IDC_BUTTON_PL_FILTER            1014
#define IDC_BUTTON_PL_SEARCH_NEXT       1015
#define IDC_BUTTON_SAVE                 1017
#define IDC_BUTTON_SEARCH_NEXT          1018
#define IDC_BUTTON_SETTINGS             1019
#define IDC_BUTTON_STOP                 1020
#define IDC_BUTTON_TEST_EPG             1021
#define IDC_SPLIT_BUTTON_UPDATE_CHANGED 1022
#define IDC_BUTTON_CHECK_ARCHIVE        1024
#define IDC_CHECK_ADULT                 1025
#define IDC_CHECK_ARCHIVE               1026
#define IDC_CHECK_CASE_SHOW             1027
#define IDC_CHECK_CUSTOMIZE             1028
#define IDC_CHECK_GLOBAL                1029
#define IDC_CHECK_SHOW_URL              1029
#define IDC_CHECK_PL_ARCHIVE            1030
#define IDC_CHECK_REGEX_SHOW            1031
#define IDC_CHECK_NOT_ADDED             1032
#define IDC_CHECK_SHOW_CHANGED          1033
#define IDC_COMBO_CHANNELS              1034
#define IDC_COMBO_PLAYLIST              1035
#define IDC_COMBO_SORT                  1036
#define IDC_CUSTOM_PLAYLIST             1037
#define IDC_EDIT_ARCHIVE_CHECK_DAYS     1038
#define IDC_EDIT_ARCHIVE_CHECK_HOURS    1039
#define IDC_EDIT_CATEGORY               1040
#define IDC_CHECK_SHOW_CHANGED_CH       1041
#define IDC_EDIT_PASSWORD               1042
#define IDC_EDIT_EPG1_ID                1043
#define IDC_EDIT_INFO_AUDIO             1044
#define IDC_EDIT_INFO_VIDEO             1045
#define IDC_EDIT_LOGIN                  1047
#define IDC_EDIT_PL_SEARCH              1048
#define IDC_EDIT_NAME                   1050
#define IDC_EDIT_SEARCH                 1051
#define IDC_EDIT_EPG_ROOT               1051
#define IDC_EDIT_STREAM_URL             1052
#define IDC_EDIT_EPG_NAME               1052
#define IDC_EDIT_EPG_DESC               1053
#define IDC_EDIT_EPG2_ID                1054
#define IDC_EDIT_EPG_START              1054
#define IDC_EDIT_URL_ID                 1055
#define IDC_EDIT_EPG_END                1055
#define IDC_EDIT_URL                    1056
#define IDC_EDIT_EPG_FMT_DATE           1056
#define IDC_MFCEDITBROWSE_PLAYER        1057
#define IDC_EDIT_EPG_FMT_TIME           1057
#define IDC_MFCEDITBROWSE_PROBE         1058
#define IDC_EDIT_EPG_TZ                 1058
#define IDC_MFCLINK_DONATE              1059
#define IDC_EDIT_SET_ID                 1059
#define IDC_PROGRESS_LOAD               1060
#define IDC_EDIT_SET_ID2                1060
#define IDC_EDIT_SET_TOKEN              1060
#define IDC_SPIN_ARCHIVE_CHECK_HOURS    1061
#define IDC_SPIN_ARCHIVE_CHECK_DAYS     1062
#define IDC_STATIC_APP_TITLE            1064
#define IDC_STATIC_CHANNELS             1066
#define IDC_STATIC_ICON                 1067
#define IDC_EDIT_ICON_NAME              1068
#define IDC_STATIC_PL_ICON              1069
#define IDC_EDIT_PL_ICON_NAME           1070
#define IDC_STATIC_PL_ID                1071
#define IDC_STATIC_PL_EPG               1072
#define IDC_STATIC_PLAYLIST             1073
#define IDC_STATIC_QR                   1074
#define IDC_STATIC_TITLE                1075
#define IDC_STATIC_PROGRESS_INFO        1076
#define IDC_TREE_CHANNELS               1077
#define IDC_TREE_PLAYLIST               1078
#define IDC_MFCLINK_DONATE_PAYPAL       1079
#define IDC_STATIC_STREAM_TYPE          1080
#define IDC_EDIT_PL_ARCHIVE_DAYS        1081
#define IDC_EDIT_TIME_SHIFT             1082
#define IDC_SPIN_TIME_SHIFT             1083
#define IDC_COMBO_PLUGIN_TYPE           1084
#define IDC_COMBO_ICON_SOURCE           1085
#define IDC_LIST_ICONS                  1086
#define IDC_EDIT_ARCHIVE_DAYS           1089
#define IDC_LIST_EPG                    1090
#define IDC_CHECK_AUTO_SYNC_CHANNELS    1091
#define IDC_LIST_INFO                   1092
#define IDC_LIST_CHANNELS               1093
#define IDC_STATIC_LOGIN                1094
#define IDC_STATIC_DEVICE_ID            1095
#define IDC_CHECK_EMBED                 1096
#define IDC_STATIC_VERSION              1097
#define IDC_STATIC_SERVER_ID            1097
#define IDC_STATIC_PROFILE              1098
#define IDC_EDIT_EPG                    1099
#define IDC_RICHEDIT_EPG                1100
#define IDC_RADIO_EPG1                  1101
#define IDC_RADIO_EPG2                  1102
#define IDC_EDIT_STREAM_THREADS         1103
#define IDC_SPIN_STREAM_THREADS         1104
#define IDC_COMBO_LANG                  1105
#define IDC_SPLIT_BUTTON_PACK           1106
#define IDC_MFCEDITBROWSE_CH_LIST_PATH  1107
#define IDC_MFCEDITBROWSE_PLUGINS_PATH  1108
#define IDC_STATIC_ICON_SIZE            1109
#define IDC_MFCEDITBROWSE_PLUGINS_PATH2 1109
#define IDC_MFCEDITBROWSE_PLUGINS_WEB_UPDATE_PATH 1109
#define IDC_CHECK_CMP_TITLE             1110
#define IDC_CHECK_CMP_ICON              1111
#define IDC_CHECK_CMP_EPG1              1112
#define IDC_CHECK_CMP_EPG2              1113
#define IDC_CHECK_CMP_ARCHIVE           1114
#define IDC_CHECK_AUTO_HIDE             1115
#define IDC_COMBO_STRING_SHOW           1116
#define IDC_CHECK_PORTABLE              1117
#define IDC_COMBO_STRING_HIDE           1118
#define IDC_CHECK_SHOW_MATCHED          1119
#define IDC_CHECK_HIDE_MATCHED          1120
#define IDC_SPIN_CHECK_UPDATE           1121
#define IDC_COMBO_DEVICE_ID             1122
#define IDC_SPLIT_BUTTON_UPDATE         1123
#define IDC_COMBO_DEVICE_ID2            1123
#define IDC_COMBO_SERVER_ID             1123
#define IDC_EDIT_UPDATE_FREQ            1124
#define IDC_CHECK_CHANNELS              1125
#define IDC_STATIC_VPORTAL              1126
#define IDC_CHECK_SHOW_UNKNOWN          1127
#define IDC_CHECK_FILE                  1129
#define IDC_EDIT_EPG_URL                1130
#define IDC_DATETIMEPICKER              1131
#define IDC_LIST_ACCOUNTS               1132
#define IDC_BUTTON_ADD                  1133
#define IDC_BUTTON_REMOVE               1134
#define IDC_BUTTON_NEW_FROM_URL         1135
#define IDC_EDIT_PLAYLIST_URL           1136
#define IDC_MFCLINK_DONATE_YOOMONEY     1137
#define IDC_PROGRESS_PROGRAM            1138
#define IDC_STATIC_CUR_TIME             1139
#define IDC_STATIC_TIME_LEFT            1140
#define IDC_MFCLINK_PROVIDER            1141
#define IDC_LIST_MOVIES                 1142
#define IDC_BUTTON_VOD                  1143
#define IDC_RICHEDIT_DESCRIPTION        1144
#define IDC_BUTTON_SEARCH               1145
#define IDC_EDIT_TOTAL_MOVIES           1146
#define IDC_COMBO_YEARS                 1147
#define IDC_COMBO_GENRES                1148
#define IDC_COMBO_CATEGORIES            1149
#define IDC_COMBO_QUALITY               1150
#define IDC_STATIC_GENRES               1151
#define IDC_COMBO_SEASON                1151
#define IDC_STATIC_CATEGORIES           1152
#define IDC_STATIC_YEAR                 1153
#define IDC_STATIC_QUALITY              1154
#define IDC_BUTTON_REFRESH              1155
#define IDC_STATIC_SEASON               1156
#define IDC_COMBO_EPISODE               1157
#define IDC_COMBO_PROFILE               1158
#define IDC_STATIC_EPISODE              1159
#define IDC_EDIT_PLUGIN_CAPTION         1160
#define IDC_MFCEDITBROWSE_PLUGIN_LOGO   1161
#define IDC_MFCEDITBROWSE_PLUGIN_BGND   1162
#define IDC_BUTTON_ADDED                1163
#define IDC_BUTTON_NOT_ADDED            1164
#define IDC_BUTTON_CHANGED              1165
#define IDC_BUTTON_HEVC                 1166
#define IDC_BUTTON_RESET                1167
#define IDC_EDIT_PLUGIN_SUFFIX          1168
#define IDC_EDIT_PLUGIN_UPDATE_URL      1169
#define IDC_EDIT_PLUGIN_UPDATE_FILE_URL 1170
#define IDC_EDIT_PLUGIN_UPDATE_VERSION  1171
#define IDC_CHECK_AUTOINCREMENT_VERSION 1172
#define IDC_EDIT_PLUGIN_UPDATE_NAME     1173
#define IDC_EDIT_PLUGIN_PACKAGE_NAME    1174
#define IDC_CHECK_CUSTOM_UPDATE_NAME    1175
#define IDC_CHECK_MAKE_WEB_UPDATE       1176
#define IDC_CHECK_CUSTOM_PACKAGE_NAME   1177
#define IDC_EDIT_PLUGIN_CHANNELS_WEB_PATH 1178
#define IDC_BUTTON_SAVE_CONFIG          1179
#define IDC_BUTTON_LOAD_CONFIG          1180
#define IDC_EDIT_TITLE                  1181
#define IDC_COMBO_ACCESS_TYPE           1182
#define IDC_EDIT_SHORT_NAME             1183
#define IDC_BUTTON_EDIT_CONFIG          1184
#define IDC_EDIT_PROVIDER_URL           1185
#define IDC_EDIT_PARSE_PATTERN          1186
#define IDC_EDIT_STREAM_TEMPLATE        1187
#define IDC_EDIT_STREAM_ARC_TEMPLATE    1188
#define IDC_EDIT_SHIFT_SUBST            1189
#define IDC_EDIT_PLAYLIST_TEMPLATE      1190
#define IDC_EDIT_DURATION               1191
#define IDC_STATIC_SUBST                1192
#define IDC_STATIC_DURATION             1193
#define IDC_COMBO_STREAM_TYPE           1194
#define IDC_COMBO_CATCHUP_TYPE          1195
#define IDC_COMBO_EPG_TYPE              1196
#define IDC_BUTTON_EPG_SHOW             1197
#define IDC_EDIT_PLUGIN_NAME            1198
#define IDC_DATETIMEPICKER_DATE         1199
#define IDC_EDIT_PARSE_PATTERN_ID       1200
#define IDC_CHECK_SQUARE_ICONS          1201
#define IDC_BUTTON_PLAYLIST_SHOW        1202
#define IDC_BUTTON_STREAM_PARSE         1203
#define IDC_BUTTON_STREAM_ID_PARSE      1204
#define ID_ADD_CATEGORY                 32771
#define ID_NEW_CHANNEL                  32772
#define ID_BTN_GET                      32773
#define ID_CHANNEL_DOWN                 32774
#define ID_CHANNEL_UP                   32775
#define ID_CHANNELMENU_PLAYARCHIVE      32776
#define ID_CHANNELMENU_SORTBY           32777
#define ID_EDIT_RENAME                  32778
#define ID_GET_STREAM_INFO              32779
#define ID_RESTORE                      32780
#define ID_NEW_CATEGORY                 32784
#define ID_PLAY_ARCHIVE                 32785
#define ID_PLAY_STREAM                  32786
#define ID_REMOVE                       32790
#define ID_SAVE                         32791
#define ID_TOGGLE_CHANNEL               32792
#define ID_UPDATE_CHANNEL               32793
#define ID_PLAYLISTMENU_SUBMENU         32795
#define ID_SYNC_TREE_ITEM               32796
#define ID_SORT_CATEGORY                32797
#define ID_ADD_TO_FAVORITE              32798
#define ID_CLEAR_STREAM_INFO            32799
#define ID_MAKE_ALL                     32800
#define ID_TOGGLE_CATEGORY              32801
#define ID_MAKE_ALL_ACCOUNTS            32802
#define ID_REMOVE_UNKNOWN               32803

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        274
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1205
#define _APS_NEXT_SYMED_VALUE           1180
#endif
#endif
